name: Labeller

on:
  pull_request_target:
    types: [closed]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: ./scripts/ci

      - name: Add release labels on merge
        run: ./scripts/ci/pr-label-issues.sh "${{ github.event.pull_request.number }}" "$GITHUB_REPOSITORY" "$GITHUB_BASE_REF" >> "$GITHUB_STEP_SUMMARY"
        if: github.repository == 'infinispan/infinispan-operator' && github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
